{{- if not .Values.existingSambaUsersSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-samba-shares.fullname" . }}-user-conf
  labels:
    {{- include "simple-samba-shares.labels" . | nindent 4 }}
data:
  users.conf: {{ .Values.sambaUsersFile | b64enc }}
...
{{ end }}
